# Generated by Django 5.2.4 on 2025-07-29 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppy', '0003_rename_user_usersession_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
