# Generated by Django 5.2.4 on 2025-07-30 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppy', '0008_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='distance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='is_direct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_mode',
            field=models.CharField(default='COD', max_length=20),
        ),
    ]
