# Generated by Django 5.2.4 on 2025-07-31 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppy', '0010_user_groups_user_is_active_user_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersession',
            name='logout_time',
        ),
        migrations.AddField(
            model_name='usersession',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
