# Generated by Django 5.2.4 on 2025-07-28 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppy', '0002_product_order_invoice_orderitem_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersession',
            old_name='User',
            new_name='user',
        ),
    ]
