# Generated by Django 5.2.4 on 2025-07-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppy', '0005_remove_cart_added_at_remove_cart_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
