# Generated by Django 5.2.4 on 2025-07-30 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppy', '0006_user_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
