# Generated by Django 5.2.4 on 2025-07-30 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppy', '0007_user_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
