# Generated by Django 5.2.4 on 2025-07-31 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppy', '0011_remove_usersession_logout_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='invoice_id',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
